port:  5000
markdown: kramdown
name: "Opportunity Index Map - Chicago Area Fair Housing Alliance"
url: http://opportunity.cafha.net
encoding: utf-8
timezone: America/Chicago
description: ""
gems:
  - jekyll-redirect-from